# This file generates the build matrix for GitHub Actions
include:
  - board: nice_nano//zmk
    shield: my_board
    snippet: zmk-usb-logging studio-rpc
  - board: nice_nano//zmk
    shield: settings_reset
